name: Linter Validate
on:
  pull_request:
    branches:
      - main
      - "release/**"
  push:
    branches:
      - main
      - "release/**"

jobs:
  linters:
    name: Linters
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: "lts/hydrogen"

      - name: Lint Prettier Fix
        run: npm run lint:prettier:fix

      - name: Lint Eslint Fix
        run: npm run lint:eslint:fix
