name: Build e Teste Snapshot
on: workflow_dispatch

jobs:
  jest:
    name: Build e Testes
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: "lts/hydrogen"

      - name: Build
        run: npm ci

      - name: Testes
        run: npm test
